import type { Metadata } from "next";
import "./globals.css";
import { Header } from "./components/Header";
import { Footer } from "./components/Footer";
import { Testimonials } from "./components/Testimonials";
import { Services } from "./components/Services";
import { About } from "./components/About";
import { WhatsappButton } from "./components/WhatsappButton";
import { Gallery } from "./components/Gallery";



export const metadata: Metadata = {
  title: "MelBeauty - Maquiagem e Cílios em São Paulo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body>
        <Header />
        {children}
        <About />
        <Services />
        <Testimonials />
        <Gallery/>
        <WhatsappButton />
        <Footer />

      </body>
    </html>
  );
}
